### PR TITLE
Import academics papers from tuf project #159 

### PR DESCRIPTION
**Pull request by rzr**
I filtered "git log docs/papers" from tuf project to include only pdf files.
Attribution is preserved and origin tracked,
I can add digests (SHA256?) if needed

URL: https://github.com/theupdateframework/specification/issues/159
Relate-to: https://github.com/theupdateframework/tuf/pull/1380
Origin: https://github.com/theupdateframework/tuf/commit/fb9aa3e5fd6b9c7a4753e8a76b77287857b6a9e8
Origin: https://github.com/theupdateframework/tuf/commit/e943048757d6e25dcde03626ff7d8aacd92d66c9
Origin: https://github.com/theupdateframework/tuf/commit/e7c4352177b838cbd3a70c975b10b745c29f77d9
Origin: https://github.com/theupdateframework/tuf/commit/bb059cd17e4711c650789f96bc8eaf5b731b7415
Origin: https://github.com/theupdateframework/tuf/commit/abf0349b05f5aec69b0491ba371ff5bf8461de3e

Cc: <@vladdd>
Cc: <@akonst>
Cc: <@jku>
Cc: <@trishankatdatadog>
Cc: <@joshuagl>

### CODE REVIEW

**Comment by joshuagl** [comment]
Thanks for taking the initiative here @rzr. We already have the papers included in the website repository here https://github.com/theupdateframework/theupdateframework.io/tree/master/static/papers

I like the idea of using this repository for "source" rather than "built" outputs and just having the PDFs of the papers exist on the website. Would be curious to hear from the other maintainers, though cc @JustinCappos @mnm678 @trishankatdatadog

**Comment by rzr** [comment]
Update: well files are already located at:
https://github.com/theupdateframework/theupdateframework.io/tree/master/static/papers

I am not sure it makes sense to duplicate them here, that said sources (latex) of those papers can be hosted here for preservation concerns.

I am planning to close this ticket unless someone has something more to say about it.

**Comment by mnm678** [comment]
I agree that referring to the paper pdfs on the website makes sense. It might be nice to include the latex source here, but I worry that that would be scope creep for this repo (~10 new source files/paper, latex backwards compatibility questions, etc). If there's interest maybe we can host those in their own repository.

**Comment by joshuagl** [comment]
Thanks for the attention to detail here @rzr .

As discussed, let's leave the website as the canonical place for these.

**Comment by rzr** [comment]
Fine for me, but please also check

https://github.com/theupdateframework/tuf/pull/1380

**Pull request closed without merging**
