### PR TITLE
Add John Kjell as TAP Editor

### PR DESCRIPTION
**Pull request by jkjell**
Based on the interest for additional TAP Editors and the conversations at KubeCon EU, I'd like to submit my name for consideration.

### CODE REVIEW

**Comment by JustinCappos** [comment]
Big +1 here!

**Review by JustinCappos — APPROVED** [review]

**Review by joshuagl — DISMISSED** [review]
+1 welcome to the team, John

Could you update the patch so that editors are sorted alphabetically by last name? 🙏

**Review by mnm678 — DISMISSED** [review]
+1 welcome!

**Review by JustinCappos — APPROVED** [review]

**Review by joshuagl — APPROVED** [review]

**Review by mnm678 — APPROVED** [review]

**Comment by mnm678** [comment]
@JustinCappos or @joshuagl should have the org-level permissions to update the GitHub team

**Comment by joshuagl** [comment]
I just sent the invite to @jkjell

**Pull request merged**
