### PR TITLE
Add dependabot config

### PR DESCRIPTION
**Pull request by joshuagl**
Adds a dependabot config to monitor for updates in the GitHub Actions we are using.

### CODE REVIEW

**Review by mnm678 — APPROVED** [review]
The CI failure is due to the date check, and the actual change ran fine, so LGTM. Is it possible to skip the date/version check for non-spec changes?

**Comment by joshuagl** [comment]
> The CI failure is due to the date check, and the actual change ran fine, so LGTM. Is it possible to skip the date/version check for non-spec changes?

It is, I've added 2fa4c01 to change check_release.py to only check version and date when _tuf-spec.md_ is in the list of modified files.

**Review by mnm678 — APPROVED** [review]
Thanks for fixing the ✅

**Comment by joshuagl** [comment]
@trishankatdatadog could you please take a look at this PR when you have a chance?

**Review by trishankatdatadog — APPROVED** [review]

**Pull request merged**
