### PR TITLE
Minor clean-ups

### PR DESCRIPTION
**Pull request by joshuagl**
Fix a cross-reference and use consistent capitalisation for all titles.

I put the version and date bump in a separate patch, as it is not clear to me whether it is required for these very minor tweaks.

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
Since there is no effective change, I don't even mind keeping it at the same spec version.

**Comment by lukpueh** [comment]
I think we should either stick to our "no merge into master without release"-policy, or change the policy, but not make exceptions.
What would be the disadvantage of incrementing the patch version even for minor patches? (I think that's what the patch version number is for)

Alternatively we can merge into draft and aggregate it with other changes that will bump the minor version.

**Review by lukpueh — APPROVED** [review]
LGTM! Thanks :)

**Comment by joshuagl** [comment]
In the spirit of #132, could I get a second review/approval @trishankatdatadog or @mnm678 ?

**Review by trishankatdatadog — APPROVED** [review]

**Pull request merged**
