### PR TITLE
Remove multi-role vestigial

### PR DESCRIPTION
**Pull request by joshuagl**
This is the change from #141 rebased after the bikeshed conversion.

### CODE REVIEW

**Review by mnm678 — APPROVED** [review]
LGTM, as long as we take into account @lukpueh's [comment](https://github.com/theupdateframework/specification/issues/140#issuecomment-743075303) from #140 regarding changes to the draft branch

**Review by mnm678 — APPROVED** [review]
LGTM

**Comment by mnm678** [comment]
@trishankatdatadog, will this fix the workflow concern from #150?

**Comment by trishankatdatadog** [comment]
> @trishankatdatadog, will this fix the workflow concern from #150?

No, because this is a separate issue/concern.

**Review by trishankatdatadog — APPROVED** [review]

**Pull request merged**
